# Ressourcen

Es gibt eine Menge weiterer gut strukturierter Ressourcen zu Python im Netz. Nachfolgend finden Sie nur eine sehr kleine Auswahl.

## Molecular Nanophotonics Group

* [Molecular Nanophotonics Group Website](https://home.uni-leipzig.de/~physik/sites/mona/)
* [Computer-based Physical Modeling Website @ MONA](https://home.uni-leipzig.de/~physik/sites/mona/teaching/periodic-lectures/introduction-to-computer-based-physical-modeling-ss-2023/)
* [Discord Channel Invitation Link for Discussions](https://discord.gg/sAYHWXQ8dj)

## Additional Advanced Courses

* Rosenow Group (Theory), Master Course on [Statistical Mechanics of Deep Learning](https://home.uni-leipzig.de/stp/Statistical_Deep_SS21.html)

## Python Documentation

* [Python](https://docs.python.org/3.7/)
* [Matplotlib](https://matplotlib.org/3.2.1/users/index.html)
* [Pandas](https://pandas.pydata.org/docs/getting_started/10min.html)

## Python Tutorials

* [Introduction to Python for Science](https://physics.nyu.edu/pine/pymanual/html/pymanMaster.html)
* [Nice MatPlotLib tutorial](https://github.com/rougier/matplotlib-tutorial)

## Julia Tutorial

* [Julia Programming Language](https://julialang.org)

## Pluto NoteBook

* [Pluto GitHub Webpage](https://github.com/fonsp/Pluto.jl)
```

In this conversion:

1. I've changed the RST headers to Markdown headers, using `#` for the main title and `##` for subheadings.
2. The links have been converted from RST format to Markdown format.
3. The overall structure remains the same, but it's now in Quarto-compatible Markdown syntax.
